apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -staging
namespace: staging

replicas:
  - name: web-app
    count: 3

configMapGenerator:
  - name: app-config
    behavior: create
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
      - FEATURE_FLAG=beta

patches:
  - path: patch.yaml
