apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod
namespace: prod

replicas:
  - name: web-app
    count: 5

configMapGenerator:
  - name: app-config
    behavior: create
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn
      - FEATURE_FLAG=stable

patches:
  - path: patch.yaml
