apiVersion: builtin
kind: LabelTransformer
metadata:
  name: common-labels
labels:
  app.kubernetes.io/name: web-app
  app.kubernetes.io/instance: "{{.Environment}}"
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: kustomize-capstone
  app.kubernetes.io/managed-by: kustomize
fieldSpecs:
  - path: metadata/labels
    create: true
  - path: spec/selector/matchLabels
    create: true
  - path: spec/template/metadata/labels
    create: true
