apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: kustomize-capstone
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
